#!/usr/bin/env bash

WHITE='\033[1;37m'
NC='\033[0m'
EXEC='no'

# Source the ".env" file
if [ -f ./.env ]; then
    source ./.env
fi

# If ./stripe update is run, update the stripe-cli image by pulling the latest version
if [ "$1" == "update" ]; then
    docker pull stripe/stripe-cli:latest
    exit 0
fi

if [ $# -gt 0 ]; then
    docker run --rm -it stripe/stripe-cli:latest "$@" \
        --api-key "$STRIPE_SECRET_KEY"

else
    echo -e "${WHITE}No command specified. Use './stripe help' for a list of commands.${NC}" >&2
fi
