#!/usr/bin/env bash

WHITE='\033[1;37m'
NC='\033[0m'
EXEC='no'

# Source the ".env" file
if [ -f ./.env ]; then
    source ./.env
fi

if [ $# -gt 0 ]; then
    docker run --rm -it stripe/stripe-cli:latest "$@" \
        --api-key "$STRIPE_SECRET_KEY"

else
    echo -e "${WHITE}No command specified. Type 'help' for a list of commands.${NC}" >&2
fi
